Create Problem_Statement_57_Solution.java
Mozilla-Campus-Club-Cummins/Hacktoberfest_Moz_Cummins pull request #75
Opened 2021-10-02 05:20 UTC by yashasvi17rawat

2021-10-02 06:10 UTC, Krush2311 requested changes

2021-10-02 06:10 UTC, Krush2311 commented on Solutions/Problem_Statement_57_Solution.java
> +		Student obj1=new Student("Riya");//created an object of Student class while passing parameter as name
@yashasvi17rawat We get an output: 
Riya
Unknown
which is correct!
But I would like to have an user defined program. Could you please do the needful changes?

2021-10-02 06:45 UTC, yashasvi17rawat commented
For user defined can I use switch case to give a choice to user if it wants
to enter a name or not and then respectively print the name or unknown as
an output..?

After the changes Ill again have to give pull request?

Thanking you.

On Sat, Oct 2, 2021, 11:40 AM Krushna ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In Solutions/Problem_Statement_57_Solution.java
> <https://github.com/Mozilla-Campus-Club-Cummins/Hacktoberfest_Moz_Cummins/pull/75#discussion_r720633877>
> :
>
> > @@ -0,0 +1,32 @@
> +/*
> +...
> +Write a program to print the names of students by creating a Student class. If no name is passed
> +while creating an object of Student class, then the name should be "Unknown", otherwise the name
> +should be equal to the String value passed while creating object of Student class.
> +....
> +*/
> +class Hack//creating a class hack
> +{
> +	public static void main(String[] args)
> +	{
> +		Student obj1=new Student("Riya");//created an object of Student class while passing parameter as name
>
> @yashasvi17rawat <https://github.com/yashasvi17rawat> We get an output:
> Riya
> Unknown
> which is correct!
> But I would like to have an user defined program. Could you please do the
> needful changes?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Mozilla-Campus-Club-Cummins/Hacktoberfest_Moz_Cummins/pull/75#pullrequestreview-769466874>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARIFG47MGTYLE5ZQIUM4AADUE2O6RANCNFSM5FF7SJSA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-10-02 07:37 UTC, Krush2311 commented
No! What I expect is:,
Output:
Enter name:
(User enters name and presses enter .After this the output is the input given by the user. But if nothing is provided and only enter is pressed then output is "unknown ")

2021-10-04 03:55 UTC, yashasvi17rawat commented
i have made the changes and created another pull request yesterday.

2021-10-04 04:44 UTC, Krush2311 commented
> i have made the changes and created another pull request yesterday.
Okay

2021-10-04 05:46 UTC, Shr03mink commented
@yashasvi17rawat you don't have to create a new PR every time you make a change in code. simple push new changes and they will be rebased with the earlier commit. For a detailed info, go through our Revision Video that we shared the day before yesterday

2021-10-04 05:46 UTC, closed without merging